/**:
  ros__parameters:
      # mppi
      horizon : 25
      num_samples : 3000
      u_min : [-2.0, -0.25] # accel(m/s2), steer angle(rad)
      u_max : [2.0, 0.25]
      sigmas : [0.5, 0.1] # sample range
      lambda : 1.0 
      auto_lambda : false
      # reference path
      DL : 0.1
      loolahead_distance : 3.0
      reference_path_interval : 0.85
      # cost weights
      Qc : 2.0
      Ql : 3.0
      Qv : 2.0
      Qo : 10000.0
      Qin : 0.01
      Qdin : 0.5
      # model param
      delta_t : 0.1
      vehicle_L : 1.0
      V_MAX : 8.0

