/**:
  ros__parameters:
    wheel_radius: 0.24
    wheel_width: 0.18 # wheel width of the rear wheel
    wheel_base: 1.087 # between front wheel center and rear wheel center
    wheel_tread: 1.12 # between rear left wheel center and rear right wheel center
    front_overhang: 0.467 # between front wheel center and vehicle front
    rear_overhang: 0.510 # between rear wheel center and vehicle rear
    left_overhang: 0.09 # between rear left wheel center and vehicle left (the half of the rear wheel width)
    right_overhang: 0.09 # between rear right wheel center and vehicle right (the half of the rear wheel width)
    vehicle_height: 2.2 # vehicle height + sensor_kit height
    max_steer_angle: 0.64 # [rad]
